/**
 * Official/traditional corner names, keyed by circuit and FastF1 corner
 * number. CURATED display labels, not FastF1 data -- FastF1 only numbers
 * corners. Numbering follows the official circuit maps, which is also what
 * FastF1's circuit info uses. Corners without a widely used name (e.g. the
 * unnamed kinks at Suzuka) are simply absent and render as "Turn N" alone.
 */
export const CORNER_NAMES: Record<string, Record<number, string>> = {
  silverstone: {
    1: "Abbey",
    2: "Farm Curve",
    3: "Village",
    4: "The Loop",
    5: "Aintree",
    6: "Brooklands",
    7: "Luffield",
    8: "Woodcote",
    9: "Copse",
    10: "Maggotts",
    11: "Maggotts",
    12: "Becketts",
    13: "Becketts",
    14: "Chapel",
    15: "Stowe",
    16: "Vale",
    17: "Club",
    18: "Club",
  },
  monaco: {
    1: "Sainte Dévote",
    2: "Beau Rivage",
    3: "Massenet",
    4: "Casino Square",
    5: "Mirabeau Haute",
    6: "Fairmont Hairpin",
    7: "Mirabeau Bas",
    8: "Portier",
    9: "Tunnel",
    10: "Nouvelle Chicane",
    11: "Nouvelle Chicane",
    12: "Tabac",
    13: "Louis Chiron",
    14: "Piscine",
    15: "Piscine",
    16: "Piscine",
    17: "Rascasse",
    18: "Antony Noghès",
    19: "Antony Noghès",
  },
  monza: {
    1: "Variante del Rettifilo",
    2: "Variante del Rettifilo",
    3: "Curva Grande",
    4: "Variante della Roggia",
    5: "Variante della Roggia",
    6: "Lesmo 1",
    7: "Lesmo 2",
    8: "Variante Ascari",
    9: "Variante Ascari",
    10: "Variante Ascari",
    11: "Parabolica",
  },
  suzuka: {
    1: "First Curve",
    2: "First Curve",
    3: "S Curves",
    4: "S Curves",
    5: "S Curves",
    6: "S Curves",
    7: "Dunlop Curve",
    8: "Degner 1",
    9: "Degner 2",
    11: "Hairpin",
    13: "Spoon Curve",
    14: "Spoon Curve",
    15: "130R",
    16: "Casio Triangle",
    17: "Casio Triangle",
    18: "Last Curve",
  },
  spa: {
    1: "La Source",
    2: "Eau Rouge",
    3: "Raidillon",
    4: "Raidillon",
    5: "Les Combes",
    6: "Les Combes",
    7: "Malmedy",
    8: "Bruxelles",
    10: "Pouhon",
    11: "Pouhon",
    12: "Fagnes",
    13: "Fagnes",
    14: "Campus",
    15: "Curve Paul Frère",
    16: "Blanchimont",
    17: "Blanchimont",
    18: "Bus Stop",
    19: "Bus Stop",
  },
};

export function officialCornerName(circuitId: string, cornerNumber: number): string | null {
  return CORNER_NAMES[circuitId]?.[cornerNumber] ?? null;
}
